#!/usr/bin/env bash
#
# Regenerates the workspace-root .gitignore so every git repository under
# ~/desk/projects/pulse is excluded, including nested submodules at any depth.
#
# Usage:
#   ./scripts/update-workspace-gitignore.sh
#
# Re-run after cloning a new repo into this workspace, or install the optional
# pre-commit hook via ./scripts/install-workspace-hooks.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/.gitignore"
MANUAL="${ROOT}/.gitignore.manual"

# Directories we never descend into while scanning non-git trees.
PRUNE_NAMES=(node_modules .next dist build coverage .turbo .cache)

# Build find prune expression: ( -name node_modules -o -name .next ... ) -prune
prune_expr=()
for name in "${PRUNE_NAMES[@]}"; do
    prune_expr+=( -name "$name" )
done

collect_nested_git_roots() {
    local scan_root="$1"
    find "$scan_root" \
        \( "${prune_expr[@]}" \) -type d -prune \
        -o \( -name .git \) -print -prune \
        2>/dev/null
}

# Returns 0 when $1 is already covered by an entry in $2 (prefix match).
is_covered_by() {
    local candidate="$1"
    shift
    local existing
    for existing in "$@"; do
        if [[ "$candidate" == "$existing" || "$candidate" == "$existing/"* ]]; then
            return 0
        fi
    done
    return 1
}

repo_roots=()

# Top-level git repositories: ignore the whole tree without scanning inside.
for entry in "$ROOT"/*/; do
    [[ -e "${entry}.git" ]] || continue
    repo_roots+=("$(basename "${entry%/}")")
done

# Non-git top-level trees: discover nested git repos / submodules at any depth.
for entry in "$ROOT"/*/; do
    [[ -e "${entry}.git" ]] && continue

    while IFS= read -r git_path; do
        [[ -z "$git_path" ]] && continue
        repo_dir="${git_path%/.git}"
        repo_dir="${repo_dir#"$ROOT"/}"
        repo_dir="${repo_dir%/}"
        repo_roots+=("$repo_dir")
    done < <(collect_nested_git_roots "$entry")
done

# Deduplicate and drop paths already covered by a parent repo root.
filtered_roots=()
while IFS= read -r root_path; do
    [[ -z "$root_path" ]] && continue
    if ((${#filtered_roots[@]} > 0)) && is_covered_by "$root_path" "${filtered_roots[@]}"; then
        continue
    fi
    filtered_roots+=("$root_path")
done < <(printf '%s\n' "${repo_roots[@]}" | LC_ALL=C sort -u)

{
    echo "# AUTO-GENERATED by scripts/update-workspace-gitignore.sh"
    echo "# Re-run that script (or install the pre-commit hook) after cloning repos."
    echo "#"
    echo "# Tracks workspace-only files: config, docs, scripts, and non-git folders."
    echo "# Excludes any directory that contains a .git file or folder (any depth)."
    echo ""
    echo "# --- Manual exclusions (edit .gitignore.manual) ---"
    if [[ -f "$MANUAL" ]]; then
        cat "$MANUAL"
    else
        echo ".DS_Store"
    fi
    echo ""
    echo "# --- Auto-detected git repositories ---"
    if ((${#filtered_roots[@]} == 0)); then
        echo "# (none detected)"
    else
        for root_path in "${filtered_roots[@]}"; do
            printf '%s/\n' "$root_path"
        done
    fi
} >"$OUT"

echo "Wrote ${OUT} (${#filtered_roots[@]} git repo roots excluded)"
