#!/usr/bin/env bash
#
# Regenerates workspace config so git repositories under ~/desk/projects/pulse
# are excluded from backup and IDE source-control noise:
#   - .gitignore              (git backup exclusions)
#   - .vscode/settings.json   (Cursor/VS Code workspace git + explorer settings)
#   - pulse.code-workspace    (same git settings when opened as a workspace file)
#
# Usage:
#   ./scripts/update-workspace-gitignore.sh
#
# Re-run after cloning a new repo into this workspace, or install the optional
# pre-commit hook via ./scripts/install-workspace-hooks.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${ROOT}/.gitignore"
MANUAL="${ROOT}/.gitignore.manual"
VSCODE_SETTINGS="${ROOT}/.vscode/settings.json"
WORKSPACE_FILE="${ROOT}/pulse.code-workspace"

# Directories we never descend into while scanning non-git trees.
PRUNE_NAMES=(node_modules .next dist build coverage .turbo .cache)

# Build find prune expression: ( -name node_modules -o -name .next ... ) -prune
prune_expr=()
for name in "${PRUNE_NAMES[@]}"; do
    prune_expr+=( -name "$name" )
done

collect_nested_git_roots() {
    local scan_root="$1"
    find "$scan_root" \
        \( "${prune_expr[@]}" \) -type d -prune \
        -o \( -name .git \) -print -prune \
        2>/dev/null
}

# Returns 0 when $1 is already covered by an entry in $2 (prefix match).
is_covered_by() {
    local candidate="$1"
    shift
    local existing
    for existing in "$@"; do
        if [[ "$candidate" == "$existing" || "$candidate" == "$existing/"* ]]; then
            return 0
        fi
    done
    return 1
}

repo_roots=()

# Top-level git repositories: ignore the whole tree without scanning inside.
for entry in "$ROOT"/*/; do
    [[ -e "${entry}.git" ]] || continue
    repo_roots+=("$(basename "${entry%/}")")
done

# Non-git top-level trees: discover nested git repos / submodules at any depth.
for entry in "$ROOT"/*/; do
    [[ -e "${entry}.git" ]] && continue

    while IFS= read -r git_path; do
        [[ -z "$git_path" ]] && continue
        repo_dir="${git_path%/.git}"
        repo_dir="${repo_dir#"$ROOT"/}"
        repo_dir="${repo_dir%/}"
        repo_roots+=("$repo_dir")
    done < <(collect_nested_git_roots "$entry")
done

# Deduplicate and drop paths already covered by a parent repo root.
filtered_roots=()
while IFS= read -r root_path; do
    [[ -z "$root_path" ]] && continue
    if ((${#filtered_roots[@]} > 0)) && is_covered_by "$root_path" "${filtered_roots[@]}"; then
        continue
    fi
    filtered_roots+=("$root_path")
done < <(printf '%s\n' "${repo_roots[@]}" | LC_ALL=C sort -u)

{
    echo "# AUTO-GENERATED by scripts/update-workspace-gitignore.sh"
    echo "# Re-run that script (or install the pre-commit hook) after cloning repos."
    echo "#"
    echo "# Tracks workspace-only files: config, docs, scripts, and non-git folders."
    echo "# Excludes any directory that contains a .git file or folder (any depth)."
    echo ""
    echo "# --- Manual exclusions (edit .gitignore.manual) ---"
    if [[ -f "$MANUAL" ]]; then
        cat "$MANUAL"
    else
        echo ".DS_Store"
    fi
    echo ""
    echo "# --- Auto-detected git repositories ---"
    if ((${#filtered_roots[@]} == 0)); then
        echo "# (none detected)"
    else
        for root_path in "${filtered_roots[@]}"; do
            printf '%s/\n' "$root_path"
        done
    fi
} >"$OUT"

write_vscode_settings() {
    mkdir -p "$(dirname "$VSCODE_SETTINGS")"

    # Folder-name scan skips (VS Code matches directory names, not full paths).
    scan_ignored=(node_modules .next dist build coverage .turbo .cache)
    for entry in "$ROOT"/*/; do
        [[ -e "${entry}.git" ]] || continue
        scan_ignored+=("$(basename "${entry%/}")")
    done

    # shellcheck disable=SC2012
    ROOT="$ROOT" VSCODE_SETTINGS="$VSCODE_SETTINGS" WORKSPACE_FILE="$WORKSPACE_FILE" \
        SCAN_IGNORED_JSON="$(printf '%s\n' "${scan_ignored[@]}" | LC_ALL=C sort -u | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')" \
        REPO_PATHS_JSON="$(printf '%s\n' "${filtered_roots[@]}" | python3 -c 'import json,sys; print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))')" \
        python3 <<'PY'
import json
import os
from pathlib import Path

root = Path(os.environ["ROOT"])
vscode_settings = Path(os.environ["VSCODE_SETTINGS"])
workspace_file = Path(os.environ["WORKSPACE_FILE"])
repo_manifest = root / ".vscode" / ".generated-repo-paths.json"
scan_ignored = json.loads(os.environ["SCAN_IGNORED_JSON"])
repo_paths = json.loads(os.environ["REPO_PATHS_JSON"])

managed_git_keys = {
    "git.autoRepositoryDetection",
    "git.detectSubmodules",
    "git.repositoryScanIgnoredFolders",
}

managed_exclude_keys = {
    "files.exclude",
    "search.exclude",
}

generated_git_settings = {
    "git.autoRepositoryDetection": "openEditors",
    "git.detectSubmodules": False,
    "git.repositoryScanIgnoredFolders": scan_ignored,
}


def load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    text = "\n".join(
        line for line in text.splitlines() if not line.lstrip().startswith("//")
    )
    return json.loads(text) if text.strip() else {}


def load_manifest():
    if not repo_manifest.exists():
        return []
    data = json.loads(repo_manifest.read_text(encoding="utf-8"))
    return data if isinstance(data, list) else []


def save_manifest(paths):
    repo_manifest.parent.mkdir(parents=True, exist_ok=True)
    repo_manifest.write_text(
        json.dumps(sorted(paths), indent=4) + "\n",
        encoding="utf-8",
    )


def merge_exclude_map(existing, old_paths, new_paths):
    merged = dict(existing or {})
    for path in old_paths:
        merged.pop(path, None)
    for path in new_paths:
        merged[path] = True
    return merged


def merge_settings(existing: dict) -> dict:
    merged = dict(existing)
    for key in managed_git_keys:
        merged.pop(key, None)
    merged.update(generated_git_settings)

    previous_repo_paths = load_manifest()
    for key in managed_exclude_keys:
        merged[key] = merge_exclude_map(
            merged.get(key),
            previous_repo_paths,
            repo_paths,
        )

    save_manifest(repo_paths)
    return merged


def write_vscode_settings_file(merged_settings: dict) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/update-workspace-gitignore.sh",
        "// Re-run after cloning repos. Managed git + explorer keys are overwritten.",
        json.dumps(merged_settings, indent=4),
        "",
    ]
    vscode_settings.write_text("\n".join(lines), encoding="utf-8")


def write_workspace_file(merged_settings: dict) -> None:
    workspace = {"folders": [{"path": "."}], "settings": {}}
    if workspace_file.exists():
        with workspace_file.open(encoding="utf-8") as handle:
            workspace = json.load(handle)
    if "folders" not in workspace:
        workspace["folders"] = [{"path": "."}]
    workspace["settings"] = merged_settings
    with workspace_file.open("w", encoding="utf-8") as handle:
        json.dump(workspace, handle, indent="\t")
        handle.write("\n")


existing = load_json(vscode_settings)
merged = merge_settings(existing)
write_vscode_settings_file(merged)
write_workspace_file(merged)
PY
}

write_vscode_settings

echo "Wrote ${OUT} (${#filtered_roots[@]} git repo roots excluded)"
echo "Wrote ${VSCODE_SETTINGS} and updated ${WORKSPACE_FILE} (workspace git SCM + explorer exclusions)"
